### ISSUE TITLE
Animación

### ISSUE THREAD

**Issue by Letzycdol** [kaligocas/AnimacionesJs#1]
Corazones animados

```html
<div class="hearts">
  <div class="heart"></div>
  <div class="heart"></div>
  <div class="heart"></div>
</div>
```

CSS:
```css
@keyframes float {
  0% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-20px);
  }
  100% {
    transform: translateY(0);
  }
}

.heart {
  width: 50px;
  height: 50px;
  background-color: red;
  position: absolute;
  transform: rotate(-45deg);
}

.heart:nth-child(1) {
  top: 10%;
  left: 10%;
}

.heart:nth-child(2) {
  top: 10%;
  left: 40%;
}

.heart:nth-child(3) {
  top: -10%;
  left: 25%;
}

.hearts {
  position: relative;
}

.heart {
  animation: float 1s ease-in-out infinite;
}
```
